# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-16 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.CharField(default='This instance was created before altering the model!', max_length=255),
        ),
    ]
